const candyProducts = [
  {
    id: 1,
    price: 25.5,
    name: "Frugt Vingummibamser",
    image: "./images/1.jpg",
    country: "Germany",
    description: "The original classic gummy bears from Haribo. A colorful mix of fruity flavors including strawberry, lemon, and pineapple. Chewy, sweet, and loved by kids and adults alike since 1922.",
    weight: 250, // weight in grams
    color: ["Red", "Green", "Yellow", "Orange"],
    discount: 0, // discount in percent
    brand: "Haribo",
    category: "Vingummi",
    allergies: ["None"],
    dateAdded: "2023-10-15",
  },
  {
    id: 2,
    price: 45.0,
    name: "Cremet Mælkechokolade",
    image: "./images/2.jpg",
    country: "Switzerland",
    description:"Experience the smooth, melting sensation of premium Swiss milk chocolate. Crafted by Lindt's Master Chocolatiers, this bar offers a rich, velvety texture and a perfectly balanced cocoa sweetness.",
    weight: 100,
    color: ["Brown"],
    discount: 15, // 15% discount
    brand: "Lindt",
    category: "Chokolade",
    allergies: ["Mælk", "Nødder", "Soja"],
    dateAdded: "2023-11-01",
  },
  {
    id: 3,
    price: 18.0,
    name: "Sure Jordbær Snører",
    image: "./images/3.jpg",
    country: "Denmark",
    description: "These sour strawberry licorice ropes from Malaco are a tangy treat for those who love a bit of zing. Each bite delivers a burst of sweet and sour strawberry flavor, making them a favorite among candy enthusiasts.",
    weight: 120,
    color: ["Red"],
    discount: 0,
    brand: "Malaco",
    category: "Lakrids/Snører",
    allergies: ["Gluten"],
    dateAdded: "2023-11-10",
  },
  {
    id: 4,
    price: 32.0,
    name: "Salte Heksehyl",
    image: "./images/4.jpg",
    country: "Netherlands",
    description: "Toms' Salty Heksehyl is a unique blend of salty and sweet flavors. These licorice pieces are coated with a layer of salt, creating a delicious contrast to the rich, chewy licorice inside. Perfect for those who enjoy a bold taste experience.",
    weight: 200,
    color: ["Black", "White"],
    discount: 5,
    brand: "Toms",
    category: "Lakrids",
    allergies: ["Gluten"],
    dateAdded: "2023-09-20",
  },
  {
    id: 5,
    price: 15.0,
    name: "Klassiske Bolcher",
    image: "./images/5.jpg",
    country: "Denmark",
    description: "These classic Danish bolcher are a beloved treat with their distinctive pink and white striped appearance. Each bolcher is made with high-quality ingredients and offers a perfect balance of sweetness and texture.",
    weight: 150,
    color: ["Pink", "White"],
    discount: 0,
    brand: "Nørregade",
    category: "Bolcher",
    allergies: ["None"],
    dateAdded: "2023-11-20",
  },
];

console.log(candyProducts);
