const candyProducts = [
  {
    id: 1,
    price: 25.5,
    name: "Fruit Gummy Bears",
    image: "./images/1.jpg",
    country: "Denmark",
    description: "The original classic gummy bears from Haribo. A colorful mix of fruity flavors including strawberry, lemon, and pineapple. Chewy, sweet, and loved by kids and adults alike since 1922.",
    weight: 250, // weight in grams
    color: ["Red", "Green", "Yellow", "Orange"],
    discount: 0, // discount in percent
    brand: "Haribo",
    category: "Vingummi",
    allergies: ["None"],
    dateAdded: "2023-10-15",
  },
  {
    id: 2,
    price: 45.0,
    name: "Creamy Milk Chocolate",
    image: "./images/2.jpg",
    country: "Denmark",
    description:"Experience the smooth, melting sensation of premium Swiss milk chocolate. Crafted by Lindt's Master Chocolatiers, this bar offers a rich, velvety texture and a perfectly balanced cocoa sweetness.",
    weight: 100,
    color: ["Brown"],
    discount: 15, // 15% discount
    brand: "Lindt",
    category: "Chokolade",
    allergies: ["Mælk", "Nødder", "Soja"],
    dateAdded: "2023-11-01",
  },
  {
    id: 3,
    price: 18.0,
    name: "Sour Strawberry Ropes",
    image: "./images/3.jpg",
    country: "Denmark",
    description: "These sour strawberry licorice ropes from Malaco are a tangy treat for those who love a bit of zing. Each bite delivers a burst of sweet and sour strawberry flavor, making them a favorite among candy enthusiasts.",
    weight: 120,
    color: ["Red"],
    discount: 0,
    brand: "Malaco",
    category: "Lakrids/Snører",
    allergies: ["Gluten"],
    dateAdded: "2023-11-10",
  },
  {
    id: 4,
    price: 32.0,
    name: "Salty Licorice Candies",
    image: "./images/4.jpg",
    country: "Denmark",
    description: "Toms' Salty Heksehyl is a unique blend of salty and sweet flavors. These licorice pieces are coated with a layer of salt, creating a delicious contrast to the rich, chewy licorice inside. Perfect for those who enjoy a bold taste experience.",
    weight: 200,
    color: ["Black", "White"],
    discount: 5,
    brand: "Toms",
    category: "Lakrids",
    allergies: ["Gluten"],
    dateAdded: "2023-09-20",
  },
  {
    id: 5,
    price: 15.0,
    name: "Classic Hard Candies",
    image: "./images/5.jpg",
    country: "Poland",
    description: "These classic candies are a beloved treat with their distinctive pink and white striped appearance. Each bolcher is made with high-quality ingredients and offers a perfect balance of sweetness and texture.",
    weight: 150,
    color: ["Pink", "White"],
    discount: 0,
    brand: "Nørregade",
    category: "Bolcher",
    allergies: ["None"],
    dateAdded: "2023-11-20",
  },
  {
    id: 6,
    price: 20.0,
    name: "Polish Chocolate Wafer Bar",
    image: "./images/6.png",
    country: "Poland",
    description: "Crispy wafer layers covered in smooth milk chocolate, a popular Polish snack.",
    weight: 180,
    color: ["Brown"],
    discount: 10,
    brand: "Wawel",
    category: "Chocolate",
    allergies: ["Milk", "Gluten"],
    dateAdded: "2023-12-01",
  },
  {
    id: 7,
    price: 17.5,
    name: "Plum Filled Chocolates",
    image: "./images/7.png",
    country: "Poland",
    description: "Soft dried plums coated in rich dark chocolate.",
    weight: 150,
    color: ["Dark Brown"],
    discount: 0,
    brand: "Solidarnosc",
    category: "Chocolate",
    allergies: ["Soy"],
    dateAdded: "2023-12-03",
  },
  {
    id: 8,
    price: 14.0,
    name: "Polish Fruit Jellies",
    image: "./images/8.jpg",
    country: "Poland",
    description: "Soft fruit-flavored jelly cubes coated in sugar.",
    weight: 160,
    color: ["Red", "Yellow", "Green"],
    discount: 5,
    brand: "Mieszko",
    category: "Jelly",
    allergies: ["None"],
    dateAdded: "2023-12-05",
  },
  {
    id: 9,
    price: 22.0,
    name: "Serbian Hazelnut Chocolate",
    image: "./images/9.jpg",
    country: "Serbia",
    description: "Creamy milk chocolate filled with roasted Balkan hazelnuts.",
    weight: 120,
    color: ["Brown"],
    discount: 0,
    brand: "Najlepse Zelje",
    category: "Chocolate",
    allergies: ["Milk", "Nuts"],
    dateAdded: "2023-12-08",
  },
  {
    id: 10,
    price: 16.5,
    name: "Fruit Caramel Chews",
    image: "./images/10.jpg",
    country: "Serbia",
    description: "Soft and chewy fruit-flavored caramel candies.",
    weight: 140,
    color: ["Red", "Orange", "Yellow"],
    discount: 5,
    brand: "Pionir",
    category: "Caramel",
    allergies: ["Milk"],
    dateAdded: "2023-12-10",
  },
  {
    id: 11,
    price: 19.0,
    name: "Serbian Cocoa Biscuits",
    image: "./images/11.jpg",
    country: "Serbia",
    description: "Chocolate-covered biscuits with a rich cocoa filling.",
    weight: 200,
    color: ["Brown"],
    discount: 0,
    brand: "Bambi",
    category: "Chocolate Biscuit",
    allergies: ["Milk", "Gluten"],
    dateAdded: "2023-12-12",
  },
  {
    id: 12,
    price: 24.0,
    name: "Greek Honey Sesame Bars",
    image: "./images/12.jpg",
    country: "Greece",
    description: "Traditional sesame bars sweetened with natural Greek honey.",
    weight: 130,
    color: ["Golden"],
    discount: 10,
    brand: "Jotis",
    category: "Sesame Bar",
    allergies: ["Sesame"],
    dateAdded: "2023-12-15",
  },
  {
    id: 13,
    price: 21.0,
    name: "Greek Milk Chocolate Bar",
    image: "./images/13.jpg",
    country: "Greece",
    description: "Smooth Mediterranean milk chocolate with a creamy finish.",
    weight: 100,
    color: ["Brown"],
    discount: 0,
    brand: "ION",
    category: "Chocolate",
    allergies: ["Milk"],
    dateAdded: "2023-12-18",
  },
  {
    id: 14,
    price: 18.5,
    name: "Loukoumi (Greek Delight)",
    image: "./images/14.jpg",
    country: "Greece",
    description: "Soft sugar-dusted cubes flavored with rose and citrus.",
    weight: 170,
    color: ["Pink", "White"],
    discount: 0,
    brand: "Loukidou",
    category: "Turkish Delight",
    allergies: ["None"],
    dateAdded: "2023-12-20",
  },
  {
    id: 15,
    price: 26.0,
    name: "Dark Chocolate with Almonds",
    image: "./images/15.jpg",
    country: "Greece",
    description: "Rich dark chocolate blended with crunchy roasted almonds.",
    weight: 150,
    color: ["Dark Brown"],
    discount: 15,
    brand: "Pavlidis",
    category: "Chocolate",
    allergies: ["Milk", "Nuts"],
    dateAdded: "2023-12-22",
  }
];

console.log(candyProducts);
